In [1]:
! pip install pandas
! pip install matplotlib

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
data_path = "../data/Rfam.pdb"

column_names = [
    'rfam_acc', 
    'pdb_id', 
    'chain', 
    'pdb_start', 
    'pdb_end', 
    'bit_score', 
    'evalue_score', 
    'cm_start', 
    'cm_end', 
    'hex_colour'
]

data = pd.read_csv(
  data_path, 
  sep='\s+',         
  header=1,      
  names=column_names, 
  comment='#'
)

data.head(10)

<>:18: SyntaxWarning: invalid escape sequence '\s'
<>:18: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_17660/3956594775.py:18: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',

,rfam_acc,pdb_id,chain,pdb_start,pdb_end,bit_score,evalue_score,cm_start,cm_end,hex_colour
0,RF00001,3j8g,A,2,117,77.2,3.200000e-17,1,119,c0af92
1,RF00001,4v64,BA,3,118,77.2,3.200000e-17,1,119,c0af92
2,RF00001,5el5,1J,5,121,100.7,2.800000e-23,1,119,c0af92
3,RF00001,6ftg,v,1,119,118.9,5.300000e-28,1,119,c0af92
4,RF00001,6ri5,x,1,121,88.8,3.300000e-20,1,119,c0af92
5,RF00001,6wu9,B,1,116,83.5,7.300000e-19,1,119,c0af92
6,RF00001,6xu8,A7,1,119,95.2,7.300000e-22,1,119,c0af92
7,RF00001,6zmo,L7,1,119,118.9,5.300000e-28,1,119,c0af92
8,RF00001,8bhf,B2,1,119,118.9,5.200000e-28,1,119,c0af92
9,RF00001,8ekb,1B,3,119,100.7,2.800000e-23,1,119,c0af92

## Features:

- rfam_acc (Rfam Accession Number)
  
  O que é: O número de acesso da família Rfam. É um identificador único e estável para cada família de RNA na base de dados Rfam (ex: RF00162 para a família T-box). 
  
  Importância: Permite que você agrupe todas as estruturas que pertencem à mesma família de RNA. É a sua chave de busca principal para a Rfam.

- pdb_id (PDB Identifier)

  O que é: O identificador único (geralmente de 4 caracteres) de uma entrada na base de dados Protein Data Bank (PDB). Cada pdb_id corresponde a um arquivo que descreve a estrutura 3D de uma ou mais moléculas biológicas.

  Importância: É o seu link para a "verdade experimental". Com este ID, você pode baixar o arquivo .pdb correspondente e visualizar a estrutura 3D real da molécula de RNA.

- chain

  O que é: A letra ou símbolo que identifica uma molécula específica (uma cadeia polimérica) dentro de um arquivo PDB. Um único arquivo PDB pode conter múltiplas cadeias de proteínas ou ácidos nucleicos.

  Importância: É crucial porque diz exatamente qual molécula dentro do arquivo PDB corresponde à família Rfam. Sem isso, você não saberia qual parte da estrutura olhar.

- pdb_start e pdb_end

  O que é: As coordenadas (número do primeiro e do último resíduo/nucleotídeo) que definem a região específica na cadeia do PDB que corresponde à família Rfam.

  Importância: Muitas vezes, a molécula de RNA no PDB é maior do que o domínio funcional descrito pela família Rfam. Estes números delimitam com precisão o trecho exato da estrutura que você deve analisar.

- bit_score

  O que é: Uma pontuação normalizada que mede a qualidade do alinhamento entre a sequência do PDB e o modelo da família Rfam.

  Importância: Quanto maior o bit_score, melhor e mais confiável é a correspondência. É uma medida direta da similaridade. É útil para filtrar e manter apenas os mapeamentos de alta qualidade.

- evalue_score (E-value)

  O que é: O "Valor Esperado" (Expect Value). É uma medida estatística que indica o número de correspondências com um bit_score igual ou superior que você esperaria encontrar por puro acaso ao pesquisar em uma base de dados de tamanho semelhante.

  Importância: Quanto menor o E-value, mais significativa é a correspondência. Um E-value muito baixo (ex: 1.5e-20) significa que é extremamente improvável que a correspondência seja uma coincidência. É o principal indicador de significância estatística.

- cm_start e cm_end

  O que é: As coordenadas de início e fim que descrevem qual parte do "Modelo de Covariância" (CM) da Rfam alinhou com a sequência do PDB. O CM é o modelo computacional que define a família de RNA.

  Importância: Informa se a estrutura do PDB corresponde ao modelo inteiro da família (ex: de 1 a 100 em um modelo de 100 posições) ou apenas a um fragmento dele. Uma correspondência completa (cm_start~1 e cm_end~tamanho do modelo) é geralmente mais valiosa.

- hex_colour

  O que é: Um código de cor hexadecimal (ex: #FF5733).

  Importância: É um dado puramente para visualização, provavelmente usado pelo website da Rfam para colorir diferentes famílias de RNA de forma consistente em gráficos e diagramas. Para a análise de dados e previsão de estruturas, esta coluna pode ser ignorada.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14708 entries, 0 to 14707
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rfam_acc      14708 non-null  object
 1   pdb_id        14708 non-null  object
 2   chain         14708 non-null  object
 3   pdb_start     14708 non-null  int64
 4   pdb_end       14708 non-null  int64
 5   bit_score     14708 non-null  float64
 6   evalue_score  14708 non-null  float64
 7   cm_start      14708 non-null  int64
 8   cm_end        14708 non-null  int64
 9   hex_colour    14708 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 1.1+ MB

In [ ]:
data.describe()

,pdb_start,pdb_end,bit_score,evalue_score,cm_start,cm_end
count,14708.000000,14708.000000,14708.000000,1.470800e+04,14708.000000,14708.000000
mean,53.425075,1331.898899,917.972151,1.800741e-09,32.292562,1316.672219
std,585.330530,1297.701508,976.666837,7.951170e-08,218.337078,1172.908699
min,1.000000,1.000000,30.500000,0.000000e+00,1.000000,19.000000
25%,1.000000,119.000000,77.200000,0.000000e+00,1.000000,119.000000
50%,1.000000,1515.000000,629.700000,6.500000e-189,1.000000,1478.000000
75%,4.000000,1869.000000,1564.700000,2.500000e-19,1.000000,1831.000000
max,15435.000000,15371.000000,3403.500000,6.600000e-06,3020.000000,3401.000000